name: 'Any Counter'
description: 'Any가 얼마나 있니?'
branding:
  color: blue
  icon: at-sign
inputs:
  slack-bot-token:
    description: "OAuth token for your Slack App Bot to sign requests to Slack's API with."
    required: true
  slack-channel-id:
    description: 'ID of the channel or conversation in Slack you would like messages posted to.'
    required: true
  slack-bot-signing-secret:
    description: 'Slack Bot Signing Secret'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
