name: 'Any Counter'
description: 'Any가 얼마나 있니?'
branding:
  color: blue
  icon: at-sign
inputs:
  slack-bot-token:
    description: '슬랙봇의 Bot Token'
    required: true
  slack-bot-signing-secret:
    description: '슬랙봇의 Signing Secret'
    required: true
  slack-channel-id:
    description: 'Any Counter를 사용할 슬랙 채널의 ID'
    required: true

runs:
  using: 'node16'
  main: 'dist/main.js'
