name: Test Run
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: Install Packages
        run: yarn
      - name: Build
        run: yarn build
      - name: Send Slack Message
        uses: ./
        id: send-slack-message
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ secrets.TEST_SLACK_CHANNEL_ID }}
          slack-bot-signing-secret: ${{ secrets.SLACK_SIGNING_SECRET }}
